#!/bin/bash
timestamp() {
    date +"%T"
}
pullFromGit() {
  # method to get the github dependecies
  # git clone https://github.com/RehanLaundrapp/seleniumdocker.git
  return
}
buildDocker() {
  #build our tests from image - but dont run
  docker build -t maven_compiling:latest .
  wait
  #build all images, including angular tests, and run selenium tests
  docker-compose -f docker-compose.yaml up \
    --abort-on-container-exit \
    --exit-code-from selenium-tests
}
tearDown() {
  # Removes continaers and networks
  docker-compose down
}
if [[ $1 = "build" ]]; then
  echo "===========================\n"
  echo "$(timestamp): Building Docker Image"
  echo "\n==========================="
  buildDocker
  wait
  echo "===========================\n"
  echo "$(timestamp): Removing Test Dependecies"
  echo "\n==========================="
  tearDown
  echo "$(timestamp): Go to the test-results on the host machine for test output"
fi