#!/bin/bash
timestamp() {
    date +"%T"
}
pullFromGit() {
  # method to get the github dependecies
  # git clone https://github.com/RehanLaundrapp/seleniumdocker.git
  return
}
buildDocker() {
  #build our tests from image - but dont run
  docker build -t maven_compiling:latest .
  wait
  #build all images, including angular tests, and run selenium tests
  docker-compose -f docker-compose.yaml up \
    --abort-on-container-exit \
    --exit-code-from rehan-test
}
tearDown() {
  docker-compose down
}
if [[ $1 = "build" ]]; then
  buildDocker
  wait
  #tearDown
fi